/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentBox: typeof import('./src/components/CommentsSection/CommentBox.vue')['default']
    CommentContent: typeof import('./src/components/CommentsSection/CommentContent.vue')['default']
    CommentInput: typeof import('./src/components/CommentsSection/CommentInput.vue')['default']
    Comments: typeof import('./src/components/Comments/index.vue')['default']
    CommentsSection: typeof import('./src/components/CommentsSection/index.vue')['default']
    copy: typeof import('./src/components/CommentsSection/CommentInput copy.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    Forum: typeof import('./src/components/forum/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
