/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner/index.vue')['default']
    CardBox: typeof import('./src/components/CardBox/index.vue')['default']
    CommentBox: typeof import('./src/components/CommentsSection/CommentBox.vue')['default']
    CommentContent: typeof import('./src/components/CommentsSection/CommentContent.vue')['default']
    CommentsSection: typeof import('./src/components/CommentsSection/index.vue')['default']
    copy: typeof import('./src/components/SvgIcon/index copy.vue')['default']
    DialogTemplate: typeof import('./src/components/DialogTemplate/index.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    'Index copy': typeof import('./src/components/SvgIcon/index copy.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
